#!bash
clear
#Instalando alguns pacotes necessarios
yum install -y epel-release

#Baixando a versao correta da release
read -p "Informe a versao do CentOS [7]" versao
versao=${versao:-7}

case "$versao" in
          6)
                rpm -Uvh https://repo.zabbix.com/zabbix/3.2/rhel/6/x86_64/zabbix-release-3.2-1.el6.noarch.rpm
                  ;;

          7)
                rpm -Uvh https://repo.zabbix.com/zabbix/3.2/rhel/7/x86_64/zabbix-release-3.2-1.el7.noarch.rpm
                  ;;
          *)
                  echo "Versao e uma informacao necessaria de ser informada"
                  exit 1
esac

read -p "Entre com o nome do servidor Zabbix [zabbix.solidtecnologia.com.br]: " servidor
servidor=${servidor:-zabbix.solidtecnologia.com.br}

#Descobrindo e setando o hostname que deve ser o mesmo nome no servidor zabbix
hostname=$(hostname)
read -p "Entre com o nome desse proxy [${hostname}]: " hostname
hostname=${servidor:-zabbix.solidtecnologia.com.br}

#Tendo tudo que é necessario, vamos instalar o Proxy e o agent conforme nosso processo
yum clean all
yum install -y zabbix-proxy-sqlite3
yum install -y zabbix-agent

#substituindo as variaveis para adequar ao nosso ambiente
sed -i "/Server=/c\Server=$servidor" /etc/zabbix/zabbix_agentd.conf
sed -i "/Server=/c\Server=$servidor" /etc/zabbix/zabbix_proxy.conf
sed -i "/Hostname=/c\Server=$hostname" /etc/zabbix/zabbix_proxy.conf
sed -i "/DBName=/c\DBName=/tmp/zabbix_proxy" /etc/zabbix/zabbix_proxy.conf

echo "Iniciando e habilitando os serviços. Nao esqueca de abrir no Firewall as portas 10050 para entrada e 10051 para saida"
case "$versao" in
          6)
                chkconfig zabbix-proxy on
                chkconfig zabbix-agent on
                service zabbix-proxy restart
                service zabbix-agent restart
                  ;;

          7)
                systemctl enable zabbix-proxy
                systemctl enable zabbix-agent
                systemctl restart zabbix-proxy
                systemctl restart zabbix-agent
                  ;;
          *)
                  echo "Versao e uma informacao necessaria de ser informada"
                  exit 1
esac
